### ISSUE TITLE
"Set time" and "Set date" not working

### ISSUE THREAD

**Issue by BlindForLove** [jerwil/Count_Up_Time#2]
Hi, it's been a while since the first version (7 years ago)

I hope you could help me with this problem.

When I upload the code everything works fine except 3 things:

1: the seconds counter does not update even in the rtc is working
2: if I move the rotatory encoder to the "The date" mode, after 2 seconds of not touching anything, the code goes automatically to "set date".
3: The same as 2 but with the time

Edit: I would be very pleased if I could get anyway to contact directly to you. tysm
Edit 2: It seems that problem 2 and 3 are caused by the rotary encoder switch, it seems like when it is not pressed, it acts like it is pressed and viceversa,  any solution to this? 
Edit 3:Solved! If anyone has the same problem just change this line:

  **if (button_state == HIGH){**
   button_hi = true;
   timeout = 0; 
  }
  else {button_hi = false;}

to this one:

  **if (button_state == LOW){**
   button_hi = true;
   timeout = 0; 
  }
  else {button_hi = false;}

**Comment by jerwil** [comment]
Thanks for taking the time to write up a solution when you figured this out! It could perhaps be the case that you are using a rotary encoder with a normally-closed button rather than a normally-open one. I would love to see the finished product when you're done!

**Comment by BlindForLove** [comment]
Hi Jerwil! it will be a pleasure to show the final product. Right now I'm seeing how to screw the lcd screen to the front, I do not dare to saw the wood because I'm not very skilled with it.

Cheers!
